### DISCUSSION TITLE
Please help with YAML

### DISCUSSION THREAD

**Discussion by adoucette** [G-Two/homeassistant-subaru#109] [General]
Hi, I've just installed this HACS integration and can start my Subaru Forester using the device page in Home Assistant. However I haven't figured out yet how to do this with YAML (e.g. in an automation or in a script).
I'd like to simply make an automation to open my garage door and start the Subaru but I cannot yet get the remote start to work.
Here's what I have so far:
service: input_button.press
    data:
      vin: [my VIN here]
    target:
      entity_id: input_button.2023_forester_touring_remote_start
Does anyone have an example of yaml that works so start the vehicle?
Thanks in advance,
Ari

**Comment by stboch** [comment]
Look for button not input button then just trigger via press code below from my example. 

```
sequence:
  - device_id: 7
    domain: button
    entity_id: button.stevencar_remote_start
    type: press
```

**Reply by adoucette** [reply]
Yes, that did it exactly, thank you.
```
alias: Start Subaru and open garage door
sequence:
  - device_id: [device ID for the Subaru - get this from the URL after clicking on the device in the "Subaru (HACS)" integration]
    domain: button
    entity_id: button.2023_forester_touring_remote_start
    type: press
  - device_id: [garage door opener device ID]
    domain: cover
    entity_id: [garage door opener cover entity ID]
    type: open
mode: single
icon: mdi:car
```
