### DISCUSSION TITLE
Car Alarm State

### DISCUSSION THREAD

**Discussion by IIAIronWolf** [G-Two/homeassistant-subaru#39] [Ideas]
Is there anyway to monitor the Subaru car alarm state? I've only ever had my alarm go off one time, and the Subaru app alerted me about it. It was accidental as I had remote started the car with my phone while inside the car, while my keys were inside. Remote starting locks the doors, so when I opened the door, the alarm went off.

**Comment by G-Two** [comment]
I took a quick look at the mobile app and don't think there is a straightforward way to do this. The push notifications are sent to the mobile phones via Firebase Cloud Messaging and not through the same API that the integration uses. I think in order to do this, the integration would need to present an FCM token to the Subaru API (similar to how the mobile app does upon login). The code that registers the token to an FCM provider doesn't appear to be in the mobile app, so presumably Subaru subscribes your mobile phone to the message topics on your behalf. Notifications, such as car alarm, are sent from Subaru to whomever their third-party FCM provider is, which then sends the FCM message to your phone, which tells the mobile app to display a notification regardless of your login status.

**Comment by stboch** [comment]
I think the only good way to get this into Home-Assistant right now would be Tasker. I will have to see if I can cheat and use the Home-Assistant Nofitication monitor to catch it. If I do I will post the blueprint here...

**Comment by stboch** [comment]
Hey do you have an android device looks like I found a way to use home-assistant app to get the notification!
```
alias: 'Test Subaru '
description: ''
trigger:
  - platform: state
    entity_id: sensor.stevens_phone_active_notification_count
    to: >-
      The Remote Door Lock request for your Abyss Blue Pearl 2020 Outback was
      successful.
    attribute: android.bigText_com.subaru.telematics.app.remote
condition: []
action:
  - service: notify.mobile_app_stevens_phone
    data:
      message: test subaru automation
mode: single
```
