### ISSUE TITLE
Feature Request: Option to enable vehicle polling only while charging

### ISSUE THREAD

**Issue by ianwestcott** [G-Two/homeassistant-subaru#50]
Currently the option to poll the vehicle for new information has two settings: Poll every 2 hours, or disabled. Given the caveat about frequent polling potentially draining the 12V battery, it makes sense that this is disabled by default. 

When charging a plug-in hybrid vehicle, it's useful to poll more frequently in order to display the charging status in Home Assistant. This can be accomplished with the following automation:

```yaml
# request vehicle data updates from Subaru while charging
---
alias: 'Request Subaru data updates while charging'
trigger:
  - platform: time_pattern
    minutes: "/30"
condition:
  - condition: state
    entity_id: binary_sensor.subaru_ev_battery_charging
    state: 'on'
action:
  - service: button.press
    data:
      entity_id: button.subaru_locate
```

However, I suspect writing such an automation may not be intuitive to many users, since it requires pressing the "Locate" button". It would be nice if this functionality was instead presented to the user as a third polling option&mdash;"Poll only while charging"&mdash;which will poll at a 30-minute interval any time the battery charging state is on.
